# Generated by Django 2.0.5 on 2018-07-31 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_mymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='upload',
            new_name='document',
        ),
    ]
